// <auto-generated />
using System;
using EShop.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.DAL.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20250308184648_UpdateCategory")]
    partial class UpdateCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShop.Core.Entities.Models.AppClaim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ClaimId");

                    b.ToTable("AppClaims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            ClaimType = "CanManageUsers",
                            Value = "مدیریت کارمندان فروشگاه"
                        },
                        new
                        {
                            ClaimId = 2,
                            ClaimType = "CanAddUsersOnShop",
                            Value = "اضافه کردن کارمند به فروشگاه"
                        },
                        new
                        {
                            ClaimId = 3,
                            ClaimType = "CanRemoveUsersOnShop",
                            Value = "حذف کارمند از فروشگاه"
                        },
                        new
                        {
                            ClaimId = 4,
                            ClaimType = "CanManageShop",
                            Value = "دسترسی به مدیریت فروشگاه"
                        },
                        new
                        {
                            ClaimId = 5,
                            ClaimType = "CanEditProducts",
                            Value = "دسترسی به ویرایش محصولات"
                        },
                        new
                        {
                            ClaimId = 6,
                            ClaimType = "CanRemoveProducts",
                            Value = "دسترسی به حذف محصولات"
                        },
                        new
                        {
                            ClaimId = 7,
                            ClaimType = "CanManageOrders",
                            Value = "دسترسی به مدیریت سفارش‌ها"
                        },
                        new
                        {
                            ClaimId = 8,
                            ClaimType = "CanManageContent",
                            Value = "دسترسی به مدیریت محتوا"
                        },
                        new
                        {
                            ClaimId = 9,
                            ClaimType = "AdminCanManageShops",
                            Value = "مدیر سایت - مدیریت فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 10,
                            ClaimType = "AdminCanEditShops",
                            Value = "مدیر سایت - ویرایش فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 11,
                            ClaimType = "AdminCanRemoveShops",
                            Value = "مدیر سایت - حذف فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 12,
                            ClaimType = "AdminCanEditProducts",
                            Value = "مدیر سایت - ویرایش محصولات"
                        },
                        new
                        {
                            ClaimId = 13,
                            ClaimType = "AdminCanRemoveProducts",
                            Value = "مدیر سایت - حذف محصولات"
                        },
                        new
                        {
                            ClaimId = 14,
                            ClaimType = "AdminCanManageOrders",
                            Value = "مدیر سایت - مدیریت سفارشات"
                        },
                        new
                        {
                            ClaimId = 15,
                            ClaimType = "AdminCanAddUsers",
                            Value = "مدیر سایت - افزودن کاربران"
                        },
                        new
                        {
                            ClaimId = 16,
                            ClaimType = "AdminCanEditUsers",
                            Value = "مدیر سایت - ویرایش کاربران"
                        },
                        new
                        {
                            ClaimId = 17,
                            ClaimType = "AdminCanRemoveUsers",
                            Value = "مدیر سایت - حذف کاربران"
                        },
                        new
                        {
                            ClaimId = 18,
                            ClaimType = "AdminCanReplayComments",
                            Value = "مدیر سایت - پاسخ به نظرات"
                        },
                        new
                        {
                            ClaimId = 19,
                            ClaimType = "AdminManageAccessUsers",
                            Value = "مدیر سایت - مدیریت دسترسی کاربران"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCategoryOnMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuType")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("productCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات الکترونیکی",
                            IconClass = "bi bi-phone",
                            IconColor = "#3b82f6",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "الکترونیک",
                            Slug = "electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ابزارهای خانگی",
                            IconClass = "bi bi-house-door",
                            IconColor = "#10b981",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "خانه و آشپزخانه",
                            Slug = "home-kitchen"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لباس و پوشاک",
                            IconClass = "bi bi-bag",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "مد و پوشاک",
                            Slug = "fashion-clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کتاب‌های مختلف",
                            IconClass = "bi bi-book",
                            IconColor = "#f59e0b",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "کتاب‌ها",
                            Slug = "books"
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم تحریر مدرسه و دفتر",
                            IconClass = "bi bi-pencil",
                            IconColor = "#ef4444",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "لوازم تحریر",
                            Slug = "stationery"
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "موبایل‌های هوشمند",
                            IconClass = "bi bi-phone-fill",
                            IconColor = "#2563eb",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "موبایل",
                            ParentId = 1,
                            Slug = "mobiles"
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات جانبی موبایل",
                            IconClass = "bi bi-headphones",
                            IconColor = "#6366f1",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لوازم جانبی موبایل",
                            ParentId = 1,
                            Slug = "mobile-accessories"
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لپ‌تاپ‌های حرفه‌ای",
                            IconClass = "bi bi-laptop",
                            IconColor = "#3b82f6",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لپ‌تاپ",
                            ParentId = 1,
                            Slug = "laptops"
                        },
                        new
                        {
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "تبلت‌های مختلف",
                            IconClass = "bi bi-tablet",
                            IconColor = "#10b981",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "تبلت",
                            ParentId = 1,
                            Slug = "tablets"
                        },
                        new
                        {
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "دوربین‌های عکاسی و فیلمبرداری",
                            IconClass = "bi bi-camera",
                            IconColor = "#6366f1",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "دوربین عکاسی",
                            ParentId = 1,
                            Slug = "cameras"
                        },
                        new
                        {
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ابزارهای موردنیاز آشپزخانه",
                            IconClass = "bi bi-utensils",
                            IconColor = "#10b981",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "ابزار آشپزخانه",
                            ParentId = 2,
                            Slug = "kitchen-tools"
                        },
                        new
                        {
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم برقی آشپزخانه",
                            IconClass = "bi bi-plug",
                            IconColor = "#2563eb",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "وسایل برقی آشپزخانه",
                            ParentId = 2,
                            Slug = "kitchen-electronics"
                        },
                        new
                        {
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "مبلمان و دکوراسیون خانه",
                            IconClass = "bi bi-couch",
                            IconColor = "#6b4226",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "مبلمان خانه",
                            ParentId = 2,
                            Slug = "home-furniture"
                        },
                        new
                        {
                            CategoryId = 14,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم خانگی برقی از قبیل یخچال، تلویزیون و...",
                            IconClass = "bi bi-tv",
                            IconColor = "#2563eb",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لوازم خانگی برقی",
                            ParentId = 2,
                            Slug = "home-appliances"
                        },
                        new
                        {
                            CategoryId = 15,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "انواع لباس‌های مردانه",
                            IconClass = "bi bi-shirt",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لباس مردانه",
                            ParentId = 3,
                            Slug = "mens-clothing"
                        },
                        new
                        {
                            CategoryId = 16,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "انواع لباس‌های زنانه",
                            IconClass = "bi bi-dress",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لباس زنانه",
                            ParentId = 3,
                            Slug = "womens-clothing"
                        },
                        new
                        {
                            CategoryId = 17,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کفش‌های مردانه و زنانه",
                            IconClass = "bi bi-shoe",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "کفش",
                            ParentId = 3,
                            Slug = "shoes"
                        },
                        new
                        {
                            CategoryId = 18,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "اکسسوری‌ها و لوازم جانبی",
                            IconClass = "bi bi-hat",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "اکسسوری",
                            ParentId = 3,
                            Slug = "accessories"
                        },
                        new
                        {
                            CategoryId = 19,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات زیبایی و بهداشتی",
                            IconClass = "bi bi-heart",
                            IconColor = "#a855f7",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "زیبایی و سلامتی",
                            Slug = "beauty-health"
                        },
                        new
                        {
                            CategoryId = 20,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "موسیقی و فیلم‌های مختلف",
                            IconClass = "bi bi-music-note",
                            IconColor = "#ef4444",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "موسیقی و فیلم",
                            Slug = "music-films"
                        },
                        new
                        {
                            CategoryId = 21,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "بازی‌های کامپیوتری و کنسول",
                            IconClass = "bi bi-controller",
                            IconColor = "#9ca3af",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "بازی‌های ویدئویی",
                            Slug = "video-games"
                        },
                        new
                        {
                            CategoryId = 22,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "مبلمان و دکوراسیون منزل",
                            IconClass = "bi bi-couch",
                            IconColor = "#6b4226",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "مبلمان",
                            Slug = "furniture"
                        },
                        new
                        {
                            CategoryId = 23,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم جانبی دیگر",
                            IconClass = "bi bi-plug",
                            IconColor = "#2563eb",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "لوازم جانبی",
                            Slug = "accessories-other"
                        },
                        new
                        {
                            CategoryId = 24,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات مربوط به خودرو",
                            IconClass = "bi bi-car-front",
                            IconColor = "#f97316",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "خودرو",
                            Slug = "automobile"
                        },
                        new
                        {
                            CategoryId = 25,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم موردنیاز سفر",
                            IconClass = "bi bi-suitcase",
                            IconColor = "#f97316",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "لوازم سفر",
                            Slug = "travel"
                        },
                        new
                        {
                            CategoryId = 26,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات تکنولوژی پیشرفته",
                            IconClass = "bi bi-gear",
                            IconColor = "#3b82f6",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "تکنولوژی",
                            Slug = "technology"
                        },
                        new
                        {
                            CategoryId = 27,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات مربوط به حیوانات خانگی",
                            IconClass = "bi bi-paw",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "حیوانات خانگی",
                            Slug = "pets"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "SuperAdmin",
                            RoleTitle = "مدیر اصلی سایت"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin",
                            RoleTitle = "مدیر سایت"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "ShopOwner",
                            RoleTitle = "صاحب فروشگاه"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "ShopManager",
                            RoleTitle = "مدیر فروشگاه"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Customer",
                            RoleTitle = "کاربر عادی"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "DeliveryAgent",
                            RoleTitle = "مسئول ارسال"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActiveCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("HasShop")
                        .HasMaxLength(300)
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "فرشاد",
                            HasShop = true,
                            IsActive = true,
                            LastName = "زمانی",
                            PhoneNumber = "09109999414"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserClaim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "ClaimId")
                        .HasName("PK_UserClaims");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductCategory", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.ProductCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserClaim", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.AppClaim", "Claim")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserClaims_Claims");

                    b.HasOne("EShop.Core.Entities.Models.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserClaims_Users");

                    b.Navigation("Claim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserRole", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Roles");

                    b.HasOne("EShop.Core.Entities.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.AppClaim", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.User", b =>
                {
                    b.Navigation("UserClaims");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
