// <auto-generated />
using System;
using EShop.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.DAL.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20250301172432_CreateClims")]
    partial class CreateClims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShop.Core.Entities.Models.AppClaim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ClaimId");

                    b.ToTable("AppClaims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            ClaimType = "CanManageUsers",
                            Value = "مدیریت کارمندان فروشگاه"
                        },
                        new
                        {
                            ClaimId = 2,
                            ClaimType = "CanAddUsersOnShop",
                            Value = "اضافه کردن کارمند به فروشگاه"
                        },
                        new
                        {
                            ClaimId = 3,
                            ClaimType = "CanRemoveUsersOnShop",
                            Value = "حذف کارمند از فروشگاه"
                        },
                        new
                        {
                            ClaimId = 4,
                            ClaimType = "CanManageShop",
                            Value = "دسترسی به مدیریت فروشگاه"
                        },
                        new
                        {
                            ClaimId = 5,
                            ClaimType = "CanEditProducts",
                            Value = "دسترسی به ویرایش محصولات"
                        },
                        new
                        {
                            ClaimId = 6,
                            ClaimType = "CanRemoveProducts",
                            Value = "دسترسی به حذف محصولات"
                        },
                        new
                        {
                            ClaimId = 7,
                            ClaimType = "CanManageOrders",
                            Value = "دسترسی به مدیریت سفارش‌ها"
                        },
                        new
                        {
                            ClaimId = 8,
                            ClaimType = "CanManageContent",
                            Value = "دسترسی به مدیریت محتوا"
                        },
                        new
                        {
                            ClaimId = 9,
                            ClaimType = "AdminCanManageShops",
                            Value = "مدیر سایت - مدیریت فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 10,
                            ClaimType = "AdminCanEditShops",
                            Value = "مدیر سایت - ویرایش فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 11,
                            ClaimType = "AdminCanRemoveShops",
                            Value = "مدیر سایت - حذف فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 12,
                            ClaimType = "AdminCanEditProducts",
                            Value = "مدیر سایت - ویرایش محصولات"
                        },
                        new
                        {
                            ClaimId = 13,
                            ClaimType = "AdminCanRemoveProducts",
                            Value = "مدیر سایت - حذف محصولات"
                        },
                        new
                        {
                            ClaimId = 14,
                            ClaimType = "AdminCanManageOrders",
                            Value = "مدیر سایت - مدیریت سفارشات"
                        },
                        new
                        {
                            ClaimId = 15,
                            ClaimType = "AdminCanAddUsers",
                            Value = "مدیر سایت - افزودن کاربران"
                        },
                        new
                        {
                            ClaimId = 16,
                            ClaimType = "AdminCanEditUsers",
                            Value = "مدیر سایت - ویرایش کاربران"
                        },
                        new
                        {
                            ClaimId = 17,
                            ClaimType = "AdminCanRemoveUsers",
                            Value = "مدیر سایت - حذف کاربران"
                        },
                        new
                        {
                            ClaimId = 18,
                            ClaimType = "AdminCanReplayComments",
                            Value = "مدیر سایت - پاسخ به نظرات"
                        },
                        new
                        {
                            ClaimId = 19,
                            ClaimType = "AdminManageAccessUsers",
                            Value = "مدیر سایت - مدیریت دسترسی کاربران"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "SuperAdmin",
                            RoleTitle = "مدیر اصلی سایت"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin",
                            RoleTitle = "مدیر سایت"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "ShopOwner",
                            RoleTitle = "صاحب فروشگاه"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "ShopManager",
                            RoleTitle = "مدیر فروشگاه"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Customer",
                            RoleTitle = "کاربر عادی"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "DeliveryAgent",
                            RoleTitle = "مسئول ارسال"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActiveCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("HasShop")
                        .HasMaxLength(300)
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "فرشاد",
                            HasShop = true,
                            IsActive = true,
                            LastName = "زمانی",
                            PhoneNumber = "09109999414"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserClaim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "ClaimId")
                        .HasName("PK_UserClaims");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserClaim", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.AppClaim", "Claim")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Claims");

                    b.HasOne("EShop.Core.Entities.Models.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserClaims_Users");

                    b.Navigation("Claim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserRole", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Roles");

                    b.HasOne("EShop.Core.Entities.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.AppClaim", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.User", b =>
                {
                    b.Navigation("UserClaims");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
