// <auto-generated />
using EShop.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.DAL.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20250227132139_InitRoles")]
    partial class InitRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShop.Core.Entities.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleTitle = "Customer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleTitle = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleTitle = "Admin"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleTitle = "ShopOwner"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleTitle = "ShopManager"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleTitle = "DeliveryAgent"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
