// <auto-generated />
using System;
using EShop.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.DAL.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20250408205414_updateCategoryFeatureValue")]
    partial class updateCategoryFeatureValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShop.Core.Entities.Models.AppClaim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ClaimId");

                    b.ToTable("AppClaims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            ClaimType = "CanManageUsers",
                            Value = "مدیریت کارمندان فروشگاه"
                        },
                        new
                        {
                            ClaimId = 2,
                            ClaimType = "CanAddUsersOnShop",
                            Value = "اضافه کردن کارمند به فروشگاه"
                        },
                        new
                        {
                            ClaimId = 3,
                            ClaimType = "CanRemoveUsersOnShop",
                            Value = "حذف کارمند از فروشگاه"
                        },
                        new
                        {
                            ClaimId = 4,
                            ClaimType = "CanManageShop",
                            Value = "دسترسی به مدیریت فروشگاه"
                        },
                        new
                        {
                            ClaimId = 5,
                            ClaimType = "CanEditProducts",
                            Value = "دسترسی به ویرایش محصولات"
                        },
                        new
                        {
                            ClaimId = 6,
                            ClaimType = "CanRemoveProducts",
                            Value = "دسترسی به حذف محصولات"
                        },
                        new
                        {
                            ClaimId = 7,
                            ClaimType = "CanManageOrders",
                            Value = "دسترسی به مدیریت سفارش‌ها"
                        },
                        new
                        {
                            ClaimId = 8,
                            ClaimType = "CanManageContent",
                            Value = "دسترسی به مدیریت محتوا"
                        },
                        new
                        {
                            ClaimId = 9,
                            ClaimType = "CanAddProducts",
                            Value = "افزودن محصولات فروشگاه"
                        },
                        new
                        {
                            ClaimId = 10,
                            ClaimType = "ManageAccessUsers",
                            Value = "مدیریت دسترسی کاربران فروشگاه"
                        },
                        new
                        {
                            ClaimId = 11,
                            ClaimType = "AdminCanManageShops",
                            Value = "مدیر سایت - مدیریت فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 12,
                            ClaimType = "AdminCanEditShops",
                            Value = "مدیر سایت - ویرایش فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 13,
                            ClaimType = "AdminCanRemoveShops",
                            Value = "مدیر سایت - حذف فروشگاه‌ها"
                        },
                        new
                        {
                            ClaimId = 14,
                            ClaimType = "AdminCanEditProducts",
                            Value = "مدیر سایت - ویرایش محصولات"
                        },
                        new
                        {
                            ClaimId = 15,
                            ClaimType = "AdminCanRemoveProducts",
                            Value = "مدیر سایت - حذف محصولات"
                        },
                        new
                        {
                            ClaimId = 16,
                            ClaimType = "AdminCanManageOrders",
                            Value = "مدیر سایت - مدیریت سفارشات"
                        },
                        new
                        {
                            ClaimId = 17,
                            ClaimType = "AdminCanAddUsers",
                            Value = "مدیر سایت - افزودن کاربران"
                        },
                        new
                        {
                            ClaimId = 18,
                            ClaimType = "AdminCanEditUsers",
                            Value = "مدیر سایت - ویرایش کاربران"
                        },
                        new
                        {
                            ClaimId = 19,
                            ClaimType = "AdminCanRemoveUsers",
                            Value = "مدیر سایت - حذف کاربران"
                        },
                        new
                        {
                            ClaimId = 20,
                            ClaimType = "AdminCanReplayComments",
                            Value = "مدیر سایت - پاسخ به نظرات"
                        },
                        new
                        {
                            ClaimId = 21,
                            ClaimType = "AdminManageAccessUsers",
                            Value = "مدیر سایت - مدیریت دسترسی کاربران"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BankAccountIBAN")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SecondaryPhoneNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "زنجان، ابهر، خیابان اصلی، پلاک ۱۲",
                            BankAccountIBAN = "IR021000001330000544121545",
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            NationalCode = "4400230147",
                            SecondaryPhoneNumber = "09058794262",
                            ShopId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsCategoryOnMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuType")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات الکترونیکی",
                            IconClass = "bi bi-phone",
                            IconColor = "#3b82f6",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "الکترونیک",
                            Slug = "electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ابزارهای خانگی",
                            IconClass = "bi bi-house-door",
                            IconColor = "#10b981",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "خانه و آشپزخانه",
                            Slug = "home-kitchen"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لباس و پوشاک",
                            IconClass = "bi bi-bag",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "مد و پوشاک",
                            Slug = "fashion-clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کتاب‌های مختلف",
                            IconClass = "bi bi-book",
                            IconColor = "#f59e0b",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "کتاب‌ها",
                            Slug = "books"
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم تحریر مدرسه و دفتر",
                            IconClass = "bi bi-pencil",
                            IconColor = "#ef4444",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "لوازم تحریر",
                            Slug = "stationery"
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "موبایل‌های هوشمند",
                            IconClass = "bi bi-phone-fill",
                            IconColor = "#2563eb",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "موبایل",
                            ParentId = 1,
                            Slug = "mobiles"
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات جانبی موبایل",
                            IconClass = "bi bi-headphones",
                            IconColor = "#6366f1",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لوازم جانبی موبایل",
                            ParentId = 1,
                            Slug = "mobile-accessories"
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لپ‌تاپ‌های حرفه‌ای",
                            IconClass = "bi bi-laptop",
                            IconColor = "#3b82f6",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لپ‌تاپ",
                            ParentId = 1,
                            Slug = "laptops"
                        },
                        new
                        {
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "تبلت‌های مختلف",
                            IconClass = "bi bi-tablet",
                            IconColor = "#10b981",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "تبلت",
                            ParentId = 1,
                            Slug = "tablets"
                        },
                        new
                        {
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "دوربین‌های عکاسی و فیلمبرداری",
                            IconClass = "bi bi-camera",
                            IconColor = "#6366f1",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "دوربین عکاسی",
                            ParentId = 1,
                            Slug = "cameras"
                        },
                        new
                        {
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ابزارهای موردنیاز آشپزخانه",
                            IconClass = "bi bi-utensils",
                            IconColor = "#10b981",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "ابزار آشپزخانه",
                            ParentId = 2,
                            Slug = "kitchen-tools"
                        },
                        new
                        {
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم برقی آشپزخانه",
                            IconClass = "bi bi-plug",
                            IconColor = "#2563eb",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "وسایل برقی آشپزخانه",
                            ParentId = 2,
                            Slug = "kitchen-electronics"
                        },
                        new
                        {
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "مبلمان و دکوراسیون خانه",
                            IconClass = "bi bi-couch",
                            IconColor = "#6b4226",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "مبلمان خانه",
                            ParentId = 2,
                            Slug = "home-furniture"
                        },
                        new
                        {
                            CategoryId = 14,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم خانگی برقی از قبیل یخچال، تلویزیون و...",
                            IconClass = "bi bi-tv",
                            IconColor = "#2563eb",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لوازم خانگی برقی",
                            ParentId = 2,
                            Slug = "home-appliances"
                        },
                        new
                        {
                            CategoryId = 15,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "انواع لباس‌های مردانه",
                            IconClass = "bi bi-shirt",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لباس مردانه",
                            ParentId = 3,
                            Slug = "mens-clothing"
                        },
                        new
                        {
                            CategoryId = 16,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "انواع لباس‌های زنانه",
                            IconClass = "bi bi-dress",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "لباس زنانه",
                            ParentId = 3,
                            Slug = "womens-clothing"
                        },
                        new
                        {
                            CategoryId = 17,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کفش‌های مردانه و زنانه",
                            IconClass = "bi bi-shoe",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "کفش",
                            ParentId = 3,
                            Slug = "shoes"
                        },
                        new
                        {
                            CategoryId = 18,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "اکسسوری‌ها و لوازم جانبی",
                            IconClass = "bi bi-hat",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 2,
                            Name = "اکسسوری",
                            ParentId = 3,
                            Slug = "accessories"
                        },
                        new
                        {
                            CategoryId = 19,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات زیبایی و بهداشتی",
                            IconClass = "bi bi-heart",
                            IconColor = "#a855f7",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "زیبایی و سلامتی",
                            Slug = "beauty-health"
                        },
                        new
                        {
                            CategoryId = 20,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "موسیقی و فیلم‌های مختلف",
                            IconClass = "bi bi-music-note",
                            IconColor = "#ef4444",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "موسیقی و فیلم",
                            Slug = "music-films"
                        },
                        new
                        {
                            CategoryId = 21,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "بازی‌های کامپیوتری و کنسول",
                            IconClass = "bi bi-controller",
                            IconColor = "#9ca3af",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "بازی‌های ویدئویی",
                            Slug = "video-games"
                        },
                        new
                        {
                            CategoryId = 22,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "مبلمان و دکوراسیون منزل",
                            IconClass = "bi bi-couch",
                            IconColor = "#6b4226",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "مبلمان",
                            Slug = "furniture"
                        },
                        new
                        {
                            CategoryId = 23,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم جانبی دیگر",
                            IconClass = "bi bi-plug",
                            IconColor = "#2563eb",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 0,
                            Name = "لوازم جانبی",
                            Slug = "accessories-other"
                        },
                        new
                        {
                            CategoryId = 24,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات مربوط به خودرو",
                            IconClass = "bi bi-car-front",
                            IconColor = "#f97316",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "خودرو",
                            Slug = "automobile"
                        },
                        new
                        {
                            CategoryId = 25,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "لوازم موردنیاز سفر",
                            IconClass = "bi bi-suitcase",
                            IconColor = "#f97316",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "لوازم سفر",
                            Slug = "travel"
                        },
                        new
                        {
                            CategoryId = 26,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات تکنولوژی پیشرفته",
                            IconClass = "bi bi-gear",
                            IconColor = "#3b82f6",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "تکنولوژی",
                            Slug = "technology"
                        },
                        new
                        {
                            CategoryId = 27,
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "محصولات مربوط به حیوانات خانگی",
                            IconClass = "bi bi-paw",
                            IconColor = "#ec4899",
                            IsCategoryOnMain = false,
                            IsDeleted = false,
                            MenuType = 1,
                            Name = "حیوانات خانگی",
                            Slug = "pets"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductGallery", b =>
                {
                    b.Property<int>("GalleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalleryId"));

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalleryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductGalleries");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductSEO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductSEOs");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductSelectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSelectCategories");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.CategoryFeatureValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CategoryFeatureValues");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.ProductFeatureValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("ProductFeatureValues");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.ProductVariantFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductFeatureValueId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeatureValueId");

                    b.HasIndex("ProductVariantId", "ProductFeatureValueId")
                        .IsUnique();

                    b.ToTable("ProductVariantFeatures");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "SuperAdmin",
                            RoleTitle = "مدیر اصلی سایت"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin",
                            RoleTitle = "مدیر سایت"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "ShopOwner",
                            RoleTitle = "صاحب فروشگاه"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "ShopManager",
                            RoleTitle = "مدیر فروشگاه"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Customer",
                            RoleTitle = "کاربر عادی"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "DeliveryAgent",
                            RoleTitle = "مسئول ارسال"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShopNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopNameFa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ShopId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Description = "فروشگاه اینترنتی مدرن با تنوع بالا در محصولات الکترونیکی، پوشاک و لوازم خانگی. ارائه دهنده بهترین قیمت‌ها با تضمین کیفیت!",
                            Email = "BazarPal_info@gmail.com",
                            FullAddress = "زنجان، ابهر، خیابان اصلی، پلاک 21",
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 36.1468m,
                            Longitude = 49.2332m,
                            OwnerId = 1,
                            PhoneNumber = "09109999414",
                            PostalCode = "445452654",
                            RegistrationDate = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShopNameEn = "BazarPal",
                            ShopNameFa = "بازارپال"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Slide", b =>
                {
                    b.Property<int>("SlideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlideId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SlideId");

                    b.ToTable("Slides");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActiveCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployeeShop")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployeeSite")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "فرشاد",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmployeeShop = true,
                            IsEmployeeSite = true,
                            LastName = "زمانی",
                            PhoneNumber = "09109999414",
                            RegistrationDate = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserClaim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "ClaimId")
                        .HasName("PK_UserClaims");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ClaimId = 20,
                            ClaimValue = "CanManageShop"
                        },
                        new
                        {
                            UserId = 1,
                            ClaimId = 21,
                            ClaimValue = "CanEditProducts"
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Employee", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Shop", "Shop")
                        .WithMany("Employees")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EShop.Core.Entities.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("EShop.Core.Entities.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Product", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductCategory", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.ProductCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductGallery", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Product", "Product")
                        .WithMany("Galleries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductSEO", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Product", "Product")
                        .WithOne("ProductSEO")
                        .HasForeignKey("EShop.Core.Entities.Models.ProductSEO", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductSelectCategory", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.ProductCategory", "ProductCategory")
                        .WithMany("ProductSelectCategory")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProductSelectCategory_ProductCategory");

                    b.HasOne("EShop.Core.Entities.Models.Product", "Product")
                        .WithMany("ProductSelectCategory")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductSelectCategory_Product");

                    b.Navigation("Product");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.CategoryFeatureValue", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.ProductCategory", "Category")
                        .WithMany("CategoryFeatureValue")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Core.Entities.Models.Products.Feature", "Feature")
                        .WithMany("CategoryFeatureValue")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.ProductFeatureValue", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Products.Feature", "Feature")
                        .WithMany("ProductFeatureValue")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EShop.Core.Entities.Models.Product", "Product")
                        .WithMany("ProductFeatureValue")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EShop.Core.Entities.Models.Product", null)
                        .WithMany("Features")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Feature");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.ProductVariant", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.ProductVariantFeature", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Products.ProductFeatureValue", "ProductFeatureValue")
                        .WithMany()
                        .HasForeignKey("ProductFeatureValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Core.Entities.Models.Products.ProductVariant", "ProductVariant")
                        .WithMany("VariantFeatures")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatureValue");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Shop", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.User", "User")
                        .WithOne("OwnedShop")
                        .HasForeignKey("EShop.Core.Entities.Models.Shop", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserClaim", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.AppClaim", "Claim")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserClaims_Claims");

                    b.HasOne("EShop.Core.Entities.Models.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserClaims_Users");

                    b.Navigation("Claim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.UserRole", b =>
                {
                    b.HasOne("EShop.Core.Entities.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Roles");

                    b.HasOne("EShop.Core.Entities.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.AppClaim", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Product", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Galleries");

                    b.Navigation("ProductFeatureValue");

                    b.Navigation("ProductSEO");

                    b.Navigation("ProductSelectCategory");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.ProductCategory", b =>
                {
                    b.Navigation("CategoryFeatureValue");

                    b.Navigation("Children");

                    b.Navigation("ProductSelectCategory");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.Feature", b =>
                {
                    b.Navigation("CategoryFeatureValue");

                    b.Navigation("ProductFeatureValue");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Products.ProductVariant", b =>
                {
                    b.Navigation("VariantFeatures");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.Shop", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("EShop.Core.Entities.Models.User", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("OwnedShop");

                    b.Navigation("UserClaims");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
