<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Services\" />
    <Folder Include="DTOs\" />
    <Folder Include="ViewModels\Admin\OtherAdminViewModels\" />
    <Folder Include="ViewModels\Admin\SuperAdminViewModels\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

</Project>
