<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Convertors\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EShop.DA\EShop.DAL.csproj" />
  </ItemGroup>

</Project>
